php:
    # Utiliser la version PHP du système
    version: ~
    # Augmenter le temps d'exécution maximum
    ini:
        memory_limit: 256M
        max_execution_time: 120
        opcache.enable: 1
        opcache.memory_consumption: 256
        opcache.max_accelerated_files: 20000
        realpath_cache_size: 4096K
        realpath_cache_ttl: 600

http:
    # Désactiver TLS pour éviter les problèmes de certificat
    tls: false
    # Augmenter le timeout du serveur
    timeout: 120 